### ISSUE TITLE
fda sdf approved drugs

### ISSUE THREAD

**Issue by Shakeel1679** [DUTchecheche/BatchVinaGUI-v2.2.0#2]
i have a library of fda approved drugs in a single sdf  for virtual screening
there are 1180 drugs
how i will create an excel file from this sdf library?
alsp pubchem cid number for each drug 1180 to create an excel file is very tedious
is there a way to create an excel file for the above?

**Comment by DUTchecheche** [comment]
You can download all the 3D structures and SMILES of FDA approved drugs from the DrugBank Database. 
Structures: https://go.drugbank.com/releases/5-1-13/downloads/approved-structures
SMILES: https://go.drugbank.com/releases/5-1-13/downloads/approved-structure-links

**Comment by DUTchecheche** [comment]
Remember to apply for an academic license for it.
